apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-configmap
  namespace: stream-processing
  labels:
    app: billing
data:
  POSTGRES_URI: "postgres-postgresql.stream-processing.svc.red.kube"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "billing"
  KAFKA_BOOTSTRAP_SERVERS: "confluent-cp-kafka.stream-processing.svc.red.kube:9092"
  KAFKA_SCHEMA_REGISTRY_URL: "http://confluent-cp-schema-registry.stream-processing.svc.red.kube:8081"
  KAFKA_STREAMS_APPLICATION_ID: "billing"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-configmap
  namespace: stream-processing
  labels:
    app: order
data:
  MONGO_HOST: "mongodb.stream-processing.svc.red.kube"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "order"
  KAFKA_BOOTSTRAP_SERVERS: "confluent-cp-kafka.stream-processing.svc.red.kube:9092"
  KAFKA_SCHEMA_REGISTRY_URL: "http://confluent-cp-schema-registry.stream-processing.svc.red.kube:8081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  namespace: stream-processing
  labels:
    app: notification
data:
  MONGO_HOST: "mongodb.stream-processing.svc.red.kube"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "notification"
  KAFKA_BOOTSTRAP_SERVERS: "confluent-cp-kafka.stream-processing.svc.red.kube:9092"
  KAFKA_SCHEMA_REGISTRY_URL: "http://confluent-cp-schema-registry.stream-processing.svc.red.kube:8081"
