apiVersion: v1
kind: Secret
metadata:
  name: billing-secret
  namespace: stream-processing
  labels:
    app: billing
stringData:
  POSTGRES_USERNAME: "billing"
  POSTGRES_PASSWORD: "billing"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: stream-processing
  labels:
    app: order
stringData:
  MONGO_USERNAME: "order"
  MONGO_PASSWORD: "order-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: stream-processing
  labels:
    app: notification
stringData:
  MONGO_USERNAME: "notification"
  MONGO_PASSWORD: "notification-password"
