kafka:
  bootstrapAddress: "localhost:9092"
  schema:
    registry:
      url: "http://localhost:8081"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications
      authentication-database: notifications

service:
  order:
    idempotency:
      ttl: 5m
